### ISSUE TITLE
Unable to create products

### ISSUE THREAD

**Issue by paul-carron** [shopizer-ecommerce/shopizer#209]
When I create Products > Create product I get a 404.

I'm only after setting this up so may have missed something. I am able to add categories though.

**Comment by runnerpaul** [comment]
Actually, I am able to create the products, its just that they always appear at the root of the catalogue. I assume this is because at no point during the product creation did I select a categroy to put them in. I didn't have the option. The closest thing  Ican see to a category option is "Product type", however ths is defaulted to GENERAL and I have no category called GENERAL.

**Comment by runnerpaul** [comment]
Not an issue.

In the create product section there is a dropdown at the top. Select product definition from here and then select a category name from the page that loads.
