### ISSUE TITLE
Higher versions of mysql 5.6 or higher are not supported.

### ISSUE THREAD

**Issue by t0rjan** [shopizer-ecommerce/shopizer#272]

**Comment by sahoora-nath** [comment]
It might be because you're using an older version of the MySQL driver. You should try using the newest version.

To get the newest version, you can check https://mvnrepository.com/artifact/mysql/mysql-connector-java

As of right now, the newest version is 8.0.13. You can add this to your pom.xml:

<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.13</version>
</dependency>

**Comment by shopizer-ecommerce** [comment]
Need to align MySQL version in pom.xml with your version installed. So far tested with version up to 5.7

**Comment by amaan-mohammed** [comment]
At the moment the pom.xml in shopizer folder has MySQL version as <mysql-jdbc-version>8.0.15</mysql-jdbc-version>
Has it been tested with MySQL 8 ?

**Comment by amaan-mohammed** [comment]
Well, i started with a vanilla installation of MySQL v8.0.15 and Shopizer was able to startup. Thats good news then.
