### ISSUE TITLE
Can we integrate gmail/facebook Login?

### ISSUE THREAD

**Issue by subodhcjoshi82** [shopizer-ecommerce/shopizer#313]
Hi 

As you know these days customer want to login via gmail/facebook or any other social media site.

Can someone please help me if these feature integrated with Shopizer? Or any tool i have to integrate to enable login via Gmail/Facebook etc?

**Comment by carlsamson** [comment]
Yes that is possible. Shopizer uses spring social in combinaison with spring security in order to login with third party authority provider such as facebook and google.

see sm-shop/src/main/resources/spring/shopizer-security.xml

You may use shopizer forum if you have further questions or need help with this

**Comment by shopizer-ecommerce** [comment]
Not an issue, please use forum
